// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function init(param) {
  
}

function update(model, param) {
  return model;
}

function view(param) {
  return /* [] */0;
}

exports.init = init;
exports.update = update;
exports.view = view;
/* No side effect */
