// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Vdom = require("bucklescript-tea/lib/js/src-ocaml/vdom.js");
var Tea_json = require("bucklescript-tea/lib/js/src-ocaml/tea_json.js");
var Tea_result = require("bucklescript-tea/lib/js/src-ocaml/tea_result.js");

function init(code) {
  return {
          value: code
        };
}

function update(model, msg) {
  return {
          value: msg[0]
        };
}

function view(model) {
  return Vdom.node(undefined, "monaco-editor", model.value, undefined, /* :: */[
              Vdom.prop("_editorValue", model.value),
              /* :: */[
                Vdom.onCB("editorValueChanged", "", (function (e) {
                        var mapper = Tea_json.Decoder.map((function (v) {
                                return /* CodeChanged */[v];
                              }), Tea_json.Decoder.at(/* :: */[
                                  "target",
                                  /* :: */[
                                    "_editorValue",
                                    /* [] */0
                                  ]
                                ], Tea_json.Decoder.string));
                        return Tea_result.result_to_option(Tea_json.Decoder.decodeEvent(mapper, e));
                      })),
                /* [] */0
              ]
            ], /* [] */0);
}

exports.init = init;
exports.update = update;
exports.view = view;
/* No side effect */
