// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");

function map(fn, v) {
  if (v !== undefined) {
    return Caml_option.some(Curry._1(fn, Caml_option.valFromOption(v)));
  }
  
}

function and_then(fn, v) {
  if (v !== undefined) {
    return Curry._1(fn, Caml_option.valFromOption(v));
  }
  
}

function orDefault(def, o) {
  if (o !== undefined) {
    return Caml_option.valFromOption(o);
  } else {
    return def;
  }
}

exports.map = map;
exports.and_then = and_then;
exports.orDefault = orDefault;
/* No side effect */
