// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Vdom = require("bucklescript-tea/lib/js/src-ocaml/vdom.js");
var Block = require("bs-platform/lib/js/block.js");
var $$Option = require("./Option.bs.js");
var Tea_html = require("bucklescript-tea/lib/js/src-ocaml/tea_html.js");
var Tea_json = require("bucklescript-tea/lib/js/src-ocaml/tea_json.js");

function openPass(param_0) {
  return /* OpenPass */Block.__(0, [param_0]);
}

function createPass(param_0) {
  return /* CreatePass */Block.__(1, [param_0]);
}

function setCreateDialog(param_0) {
  return /* SetCreateDialog */Block.__(0, [param_0]);
}

function submitCreateDialog(param_0) {
  return /* SubmitCreateDialog */Block.__(1, [param_0]);
}

function doubleClickPass(param_0) {
  return /* DoubleClickPass */Block.__(2, [param_0]);
}

function init(param) {
  return {
          createDialog: undefined
        };
}

function update(model, msg) {
  switch (msg.tag | 0) {
    case /* SetCreateDialog */0 :
        return /* tuple */[
                {
                  createDialog: msg[0]
                },
                /* DoNothing */0
              ];
    case /* SubmitCreateDialog */1 :
        var name = msg[0];
        if ($$Option.isSome(model.createDialog) && name.length !== 0) {
          return /* tuple */[
                  {
                    createDialog: undefined
                  },
                  /* CreatePass */Block.__(1, [name])
                ];
        } else {
          return /* tuple */[
                  {
                    createDialog: undefined
                  },
                  /* DoNothing */0
                ];
        }
    case /* DoubleClickPass */2 :
        return /* tuple */[
                model,
                /* OpenPass */Block.__(0, [msg[0]])
              ];
    
  }
}

function passItem(pass, active) {
  return Tea_html.li(undefined, undefined, /* :: */[
              Tea_html.classList(/* :: */[
                    /* tuple */[
                      "pass-item",
                      true
                    ],
                    /* :: */[
                      /* tuple */[
                        "active",
                        active
                      ],
                      /* [] */0
                    ]
                  ]),
              /* :: */[
                Tea_html.onDoubleClick(/* DoubleClickPass */Block.__(2, [pass.name])),
                /* [] */0
              ]
            ], /* :: */[
              Tea_html.text(pass.name),
              /* [] */0
            ]);
}

function viewHeader(model) {
  return Tea_html.div(undefined, undefined, /* :: */[
              Tea_html.class$prime("header"),
              /* [] */0
            ], /* :: */[
              Tea_html.h2(undefined, undefined, /* [] */0, /* :: */[
                    Tea_html.text("Passes"),
                    /* [] */0
                  ]),
              /* :: */[
                Tea_html.span(undefined, undefined, /* :: */[
                      Tea_html.class$prime("button"),
                      /* :: */[
                        Tea_html.onClick(/* SetCreateDialog */Block.__(0, [""])),
                        /* [] */0
                      ]
                    ], /* :: */[
                      Tea_html.text("+"),
                      /* [] */0
                    ]),
                /* [] */0
              ]
            ]);
}

function view(model, passes, active) {
  var v = model.createDialog;
  var createFileDialog = v !== undefined ? ((setTimeout(() => document.querySelector("#pass-list-create-dialog-field").focus(), 1)), Tea_html.form(undefined, undefined, /* :: */[
            Tea_html.onWithOptions(v, "submit", {
                  stopPropagation: Tea_html.defaultOptions.stopPropagation,
                  preventDefault: true
                }, Tea_json.Decoder.succeed(/* SubmitCreateDialog */Block.__(1, [v]))),
            /* [] */0
          ], /* :: */[
            Tea_html.input$prime(undefined, undefined, /* :: */[
                  Tea_html.type$prime("text"),
                  /* :: */[
                    Tea_html.classList(/* :: */[
                          /* tuple */[
                            "pass-item",
                            true
                          ],
                          /* :: */[
                            /* tuple */[
                              "create-dialog",
                              true
                            ],
                            /* [] */0
                          ]
                        ]),
                    /* :: */[
                      Tea_html.id("pass-list-create-dialog-field"),
                      /* :: */[
                        Tea_html.onBlur(/* SubmitCreateDialog */Block.__(1, [v])),
                        /* :: */[
                          Tea_html.value(v),
                          /* :: */[
                            Tea_html.onInput(undefined, (function (s) {
                                    return /* SetCreateDialog */Block.__(0, [s]);
                                  })),
                            /* [] */0
                          ]
                        ]
                      ]
                    ]
                  ]
                ], /* [] */0),
            /* [] */0
          ])) : Vdom.noNode;
  return /* tuple */[
          Tea_html.div(undefined, undefined, /* :: */[
                Tea_html.classList(/* :: */[
                      /* tuple */[
                        "pass-list",
                        true
                      ],
                      /* :: */[
                        /* tuple */[
                          "is-experiencing-input",
                          $$Option.isSome(model.createDialog)
                        ],
                        /* [] */0
                      ]
                    ]),
                /* [] */0
              ], /* :: */[
                viewHeader(model),
                /* :: */[
                  Tea_html.div(undefined, undefined, /* :: */[
                        Tea_html.class$prime("pass-items"),
                        /* [] */0
                      ], List.concat(/* :: */[
                            List.map((function (p) {
                                    return passItem(p, p.name === active);
                                  }), List.rev(passes)),
                            /* :: */[
                              /* :: */[
                                createFileDialog,
                                /* [] */0
                              ],
                              /* [] */0
                            ]
                          ])),
                  /* [] */0
                ]
              ]),
          /* :: */[
            Tea_html.noNode,
            /* [] */0
          ]
        ];
}

var doNothing = /* DoNothing */0;

exports.openPass = openPass;
exports.createPass = createPass;
exports.doNothing = doNothing;
exports.setCreateDialog = setCreateDialog;
exports.submitCreateDialog = submitCreateDialog;
exports.doubleClickPass = doubleClickPass;
exports.init = init;
exports.update = update;
exports.passItem = passItem;
exports.viewHeader = viewHeader;
exports.view = view;
/* Tea_html Not a pure module */
