// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Tea_html = require("bucklescript-tea/lib/js/src-ocaml/tea_html.js");

function init(param) {
  return {
          passes: /* [] */0
        };
}

function update(model, msg) {
  return model;
}

function passItem(pass) {
  return Tea_html.li(undefined, undefined, /* :: */[
              Tea_html.class$prime("pass-item"),
              /* [] */0
            ], /* :: */[
              Tea_html.text(pass.name),
              /* [] */0
            ]);
}

function view(model) {
  return /* tuple */[
          Tea_html.div(undefined, undefined, /* :: */[
                Tea_html.class$prime("pass-list"),
                /* [] */0
              ], /* :: */[
                Tea_html.h2(undefined, undefined, /* [] */0, /* :: */[
                      Tea_html.text("Passes"),
                      /* [] */0
                    ]),
                /* :: */[
                  Tea_html.div(undefined, undefined, /* :: */[
                        Tea_html.class$prime("pass-items"),
                        /* [] */0
                      ], List.map(passItem, model.passes)),
                  /* [] */0
                ]
              ]),
          /* :: */[
            Tea_html.noNode,
            /* [] */0
          ]
        ];
}

exports.init = init;
exports.update = update;
exports.passItem = passItem;
exports.view = view;
/* Tea_html Not a pure module */
