// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Vdom = require("bucklescript-tea/lib/js/src-ocaml/vdom.js");
var Block = require("bs-platform/lib/js/block.js");
var Tea_html = require("bucklescript-tea/lib/js/src-ocaml/tea_html.js");
var Tea_json = require("bucklescript-tea/lib/js/src-ocaml/tea_json.js");

function init(param) {
  return {
          passes: /* [] */0,
          createDialog: undefined
        };
}

function update(model, msg) {
  if (typeof msg === "number") {
    return model;
  }
  if (!msg.tag) {
    return {
            passes: model.passes,
            createDialog: msg[0]
          };
  }
  var pass = {
    name: msg[0]
  };
  return {
          passes: /* :: */[
            pass,
            model.passes
          ],
          createDialog: undefined
        };
}

function passItem(pass) {
  return Tea_html.li(undefined, undefined, /* :: */[
              Tea_html.class$prime("pass-item"),
              /* [] */0
            ], /* :: */[
              Tea_html.text(pass.name),
              /* [] */0
            ]);
}

function viewHeader(model) {
  return Tea_html.div(undefined, undefined, /* :: */[
              Tea_html.class$prime("header"),
              /* [] */0
            ], /* :: */[
              Tea_html.h2(undefined, undefined, /* [] */0, /* :: */[
                    Tea_html.text("Passes"),
                    /* [] */0
                  ]),
              /* :: */[
                Tea_html.span(undefined, undefined, /* :: */[
                      Tea_html.class$prime("button"),
                      /* :: */[
                        Tea_html.onClick(/* SetNewFileDialog */Block.__(0, [""])),
                        /* [] */0
                      ]
                    ], /* :: */[
                      Tea_html.text("+"),
                      /* [] */0
                    ]),
                /* [] */0
              ]
            ]);
}

function view(model) {
  var v = model.createDialog;
  var createFileDialog = v !== undefined ? Tea_html.form(undefined, undefined, /* :: */[
          Tea_html.onWithOptions(v, "submit", {
                stopPropagation: Tea_html.defaultOptions.stopPropagation,
                preventDefault: true
              }, Tea_json.Decoder.succeed(/* CreatePass */Block.__(1, [v]))),
          /* [] */0
        ], /* :: */[
          Tea_html.input$prime(undefined, undefined, /* :: */[
                Tea_html.type$prime("text"),
                /* :: */[
                  Tea_html.class$prime("pass-item"),
                  /* :: */[
                    Tea_html.class$prime("create-dialog"),
                    /* :: */[
                      Tea_html.autofocus(true),
                      /* :: */[
                        Tea_html.value(v),
                        /* :: */[
                          Tea_html.onInput(undefined, (function (s) {
                                  return /* SetNewFileDialog */Block.__(0, [s]);
                                })),
                          /* [] */0
                        ]
                      ]
                    ]
                  ]
                ]
              ], /* [] */0),
          /* [] */0
        ]) : Vdom.noNode;
  return /* tuple */[
          Tea_html.div(undefined, undefined, /* :: */[
                Tea_html.class$prime("pass-list"),
                /* [] */0
              ], /* :: */[
                viewHeader(model),
                /* :: */[
                  Tea_html.div(undefined, undefined, /* :: */[
                        Tea_html.class$prime("pass-items"),
                        /* [] */0
                      ], List.concat(/* :: */[
                            List.map(passItem, List.rev(model.passes)),
                            /* :: */[
                              /* :: */[
                                createFileDialog,
                                /* [] */0
                              ],
                              /* [] */0
                            ]
                          ])),
                  /* [] */0
                ]
              ]),
          /* :: */[
            Tea_html.noNode,
            /* [] */0
          ]
        ];
}

exports.init = init;
exports.update = update;
exports.passItem = passItem;
exports.viewHeader = viewHeader;
exports.view = view;
/* Tea_html Not a pure module */
