// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Json = require("@glennsl/bs-json/lib/js/src/Json.bs.js");
var List = require("bs-platform/lib/js/list.js");
var Vdom = require("bucklescript-tea/lib/js/src-ocaml/vdom.js");
var Path = require("path");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Utils = require("./Utils.bs.js");
var Global = require("./Global.bs.js");
var $$Option = require("./Option.bs.js");
var Tea_app = require("bucklescript-tea/lib/js/src-ocaml/tea_app.js");
var Tea_cmd = require("bucklescript-tea/lib/js/src-ocaml/tea_cmd.js");
var Tea_sub = require("bucklescript-tea/lib/js/src-ocaml/tea_sub.js");
var FileTree = require("./FileTree.bs.js");
var PassList = require("./PassList.bs.js");
var Tea_html = require("bucklescript-tea/lib/js/src-ocaml/tea_html.js");
var AppDomain = require("./AppDomain/AppDomain.bs.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var MonacoEditor = require("./MonacoEditor.bs.js");
var Web_document = require("bucklescript-tea/lib/js/src-ocaml/web_document.js");

function $great$great(f, g, a) {
  return Curry._1(g, Curry._1(f, a));
}

function $less$less(f, g, a) {
  return Curry._1(f, Curry._1(g, a));
}

function customSelect(value, options) {
  var createOption = function (param) {
    var msg = param[1];
    var onClick = function (e) {
      var removeActive = ((e) => e.target.parentElement.parentElement.classList.remove("active"));
      removeActive(e);
      return Caml_option.some(msg);
    };
    return Tea_html.li(undefined, undefined, /* :: */[
                Tea_html.onCB("click", "", onClick),
                /* [] */0
              ], /* :: */[
                Tea_html.text(param[0]),
                /* [] */0
              ]);
  };
  var setActive = function (e) {
    var impl = ((e) => e.target.classList.add("active"));
    impl(e);
    
  };
  return Tea_html.div(undefined, undefined, /* :: */[
              Tea_html.class$prime("custom-select"),
              /* :: */[
                Tea_html.onCB("click", "", setActive),
                /* [] */0
              ]
            ], /* :: */[
              Tea_html.text(value),
              /* :: */[
                Tea_html.img(undefined, undefined, /* :: */[
                      Tea_html.src(Utils.getStaticAssetPath("icons/select_expand_arrow.svg")),
                      /* [] */0
                    ], /* [] */0),
                /* :: */[
                  Tea_html.ul(undefined, undefined, /* :: */[
                        Tea_html.class$prime("options"),
                        /* [] */0
                      ], List.map(createOption, options)),
                  /* [] */0
                ]
              ]
            ]);
}

var unsafe_getGlobalFileTree = (function() {
    return window.__elmModel.fileTree.tree;
});

var unsafe_getGlobalProject = (function() {
    return window.__elmModel.project;
});

var unsafe_getProjectBasePath = (function() {
    return window.__elmModel.basePath;
});

function tab(param_0) {
  return /* Tab */Block.__(0, [param_0]);
}

function setVertexInputData(param_0) {
  return /* SetVertexInputData */Block.__(1, [param_0]);
}

function setFragmentShaderFile(param_0) {
  return /* SetFragmentShaderFile */Block.__(2, [param_0]);
}

function setFragmentShaderFileSearchBox(param_0) {
  return /* SetFragmentShaderFileSearchBox */Block.__(3, [param_0]);
}

function editorMsg(param_0) {
  return /* EditorMsg */Block.__(4, [param_0]);
}

function init(param) {
  return {
          tab: /* Input */0,
          editor: MonacoEditor.init("<loading...>"),
          fragmentShaderFileSearchBox: ""
        };
}

function update(model, pass, msg) {
  switch (msg.tag | 0) {
    case /* Tab */0 :
        var t = msg[0];
        if (!t) {
          return /* tuple */[
                  {
                    tab: t,
                    editor: model.editor,
                    fragmentShaderFileSearchBox: model.fragmentShaderFileSearchBox
                  },
                  /* DoNothing */0
                ];
        }
        var editor = $$Option.map(MonacoEditor.loadFile, pass.fragShader);
        return /* tuple */[
                {
                  tab: t,
                  editor: editor,
                  fragmentShaderFileSearchBox: model.fragmentShaderFileSearchBox
                },
                /* DoNothing */0
              ];
    case /* SetVertexInputData */1 :
        return /* tuple */[
                model,
                /* UpdatePassData */[{
                    name: pass.name,
                    vertexInput: msg[0],
                    fragShader: pass.fragShader
                  }]
              ];
    case /* SetFragmentShaderFile */2 :
        var v = msg[0];
        var editor$1 = MonacoEditor.loadFile(Utils.Path.absolute(v));
        return /* tuple */[
                {
                  tab: model.tab,
                  editor: editor$1,
                  fragmentShaderFileSearchBox: model.fragmentShaderFileSearchBox
                },
                /* UpdatePassData */[{
                    name: pass.name,
                    vertexInput: pass.vertexInput,
                    fragShader: Utils.Path.absolute(v)
                  }]
              ];
    case /* SetFragmentShaderFileSearchBox */3 :
        return /* tuple */[
                {
                  tab: model.tab,
                  editor: model.editor,
                  fragmentShaderFileSearchBox: msg[0]
                },
                /* DoNothing */0
              ];
    case /* EditorMsg */4 :
        var msg$1 = msg[0];
        return /* tuple */[
                {
                  tab: model.tab,
                  editor: $$Option.map((function (m) {
                          return MonacoEditor.update(m, msg$1);
                        }), model.editor),
                  fragmentShaderFileSearchBox: model.fragmentShaderFileSearchBox
                },
                /* DoNothing */0
              ];
    
  }
}

function vertexInputBlock(pass) {
  var match = pass.vertexInput;
  var value = typeof match === "number" ? (
      match !== 0 ? "" : "Fullscreen"
    ) : "Mesh";
  return Tea_html.fieldset(undefined, undefined, /* [] */0, /* :: */[
              Tea_html.label(undefined, undefined, /* [] */0, /* :: */[
                    Tea_html.text("Vertex Input Type"),
                    /* [] */0
                  ]),
              /* :: */[
                customSelect(value, /* :: */[
                      /* tuple */[
                        "Mesh",
                        /* SetVertexInputData */Block.__(1, [AppDomain.mesh(Utils.Path.absolute(""))])
                      ],
                      /* :: */[
                        /* tuple */[
                          "Fullscreen",
                          /* SetVertexInputData */Block.__(1, [/* FullScreenPass */0])
                        ],
                        /* [] */0
                      ]
                    ]),
                /* [] */0
              ]
            ]);
}

function viewVertexDataBlock(model, pass) {
  return Tea_html.div(undefined, undefined, /* :: */[
              Tea_html.class$prime("block"),
              /* [] */0
            ], /* :: */[
              Tea_html.h2(undefined, undefined, /* [] */0, /* :: */[
                    Tea_html.text("Vertex Data"),
                    /* [] */0
                  ]),
              /* :: */[
                vertexInputBlock(pass),
                /* :: */[
                  Tea_html.div(undefined, undefined, /* :: */[
                        Tea_html.styles(/* :: */[
                              /* tuple */[
                                "width",
                                "200px"
                              ],
                              /* :: */[
                                /* tuple */[
                                  "height",
                                  "50px"
                                ],
                                /* :: */[
                                  /* tuple */[
                                    "background",
                                    "blue"
                                  ],
                                  /* [] */0
                                ]
                              ]
                            ]),
                        /* :: */[
                          Tea_html.onCB("dragover", "", (function (e) {
                                  ((e.preventDefault()));
                                  ((e.dataTransfer.dropEffect = "link"));
                                  
                                })),
                          /* :: */[
                            Tea_html.onCB("drop", "", (function (e) {
                                    ((e.preventDefault()));
                                    var elemType = (e.dataTransfer.getData("application/elem-type"));
                                    if (elemType === "file") {
                                      return /* SetVertexInputData */Block.__(1, [AppDomain.mesh(Utils.Path.absolute("your mom"))]);
                                    }
                                    
                                  })),
                            /* [] */0
                          ]
                        ]
                      ], /* [] */0),
                  /* [] */0
                ]
              ]
            ]);
}

function viewUniformDataBlock(model, pass) {
  return Tea_html.div(undefined, undefined, /* :: */[
              Tea_html.class$prime("block"),
              /* [] */0
            ], /* :: */[
              Tea_html.h2(undefined, undefined, /* [] */0, /* :: */[
                    Tea_html.text("Uniform Data"),
                    /* [] */0
                  ]),
              /* [] */0
            ]);
}

function viewSamplerDataBlock(model, pass) {
  return Tea_html.div(undefined, undefined, /* :: */[
              Tea_html.class$prime("block"),
              /* [] */0
            ], /* :: */[
              Tea_html.h2(undefined, undefined, /* [] */0, /* :: */[
                    Tea_html.text("Samplers"),
                    /* [] */0
                  ]),
              /* [] */0
            ]);
}

function customSearchBox(current, setValue, getOptions, abort) {
  var createOption = function (param) {
    var msg = param[1];
    var label = param[0];
    return Tea_html.li(label, undefined, /* :: */[
                Tea_html.onCB("click", "", (function (e) {
                        var collapse = ((e) => e.target.parentElement.parentElement.classList.remove("expand"));
                        console.log(msg);
                        collapse(e);
                        return Caml_option.some(msg);
                      })),
                /* [] */0
              ], /* :: */[
                Tea_html.text(label),
                /* [] */0
              ]);
  };
  var setActive = function (e) {
    var impl = ((e) => e.target.parentElement.classList.add("expand"));
    impl(e);
    
  };
  return Tea_html.div(undefined, undefined, /* :: */[
              Tea_html.class$prime("custom-searchbox"),
              /* [] */0
            ], /* :: */[
              Tea_html.input$prime(undefined, undefined, /* :: */[
                    Tea_html.type$prime("text"),
                    /* :: */[
                      Tea_html.classList(/* :: */[
                            /* tuple */[
                              "pass-item",
                              true
                            ],
                            /* :: */[
                              /* tuple */[
                                "create-dialog",
                                true
                              ],
                              /* [] */0
                            ]
                          ]),
                      /* :: */[
                        Tea_html.id("custom-search-input"),
                        /* :: */[
                          Tea_html.onCB("focus", "", setActive),
                          /* :: */[
                            Tea_html.value(current),
                            /* :: */[
                              Tea_html.onInput(undefined, setValue),
                              /* [] */0
                            ]
                          ]
                        ]
                      ]
                    ]
                  ], /* [] */0),
              /* :: */[
                Tea_html.div(undefined, undefined, /* :: */[
                      Tea_html.class$prime("options-list"),
                      /* [] */0
                    ], List.map(createOption, Curry._1(getOptions, current))),
                /* [] */0
              ]
            ]);
}

function viewFragmentShaderBlock(model, pass) {
  return Tea_html.div(undefined, undefined, /* :: */[
              Tea_html.class$prime("block"),
              /* [] */0
            ], /* :: */[
              Tea_html.h2(undefined, undefined, /* [] */0, /* :: */[
                    Tea_html.text("Fragment Shader"),
                    /* [] */0
                  ]),
              /* :: */[
                Tea_html.fieldset(undefined, undefined, /* [] */0, /* :: */[
                      Tea_html.label(undefined, undefined, /* [] */0, /* :: */[
                            Tea_html.text("Fragment Shader File"),
                            /* [] */0
                          ]),
                      /* :: */[
                        customSearchBox(model.fragmentShaderFileSearchBox, (function (v) {
                                return /* SetFragmentShaderFileSearchBox */Block.__(3, [v]);
                              }), (function (v) {
                                var files = FileTree.findFiles((function (f) {
                                        if ($$Option.isSome(List.find_opt((function (v) {
                                                      return v === Utils.Path.extname(f);
                                                    }), /* :: */[
                                                    ".sl",
                                                    /* :: */[
                                                      ".glsl",
                                                      /* [] */0
                                                    ]
                                                  ]))) {
                                          return Utils.Path.asString(f).includes(v);
                                        } else {
                                          return false;
                                        }
                                      }), Curry._1(unsafe_getGlobalFileTree, undefined));
                                return List.map((function (v) {
                                              return /* tuple */[
                                                      Utils.Path.relative(Curry._1(unsafe_getProjectBasePath, undefined), v),
                                                      /* SetFragmentShaderFile */Block.__(2, [Utils.Path.asString(v)])
                                                    ];
                                            }), files);
                              }), /* SetFragmentShaderFileSearchBox */Block.__(3, [$$Option.orDefault("", $$Option.map(Utils.Path.asString, pass.fragShader))])),
                        /* [] */0
                      ]
                    ]),
                /* [] */0
              ]
            ]);
}

function view(model, pass) {
  var panelTabButton = function (tab) {
    var isActive = tab === model.tab;
    var label = tab ? "Fragment Shader" : "Input";
    return Tea_html.button(undefined, undefined, /* :: */[
                Tea_html.onClick(/* Tab */Block.__(0, [tab])),
                /* :: */[
                  Tea_html.classList(/* :: */[
                        /* tuple */[
                          "active",
                          isActive
                        ],
                        /* [] */0
                      ]),
                  /* [] */0
                ]
              ], /* :: */[
                Tea_html.text(label),
                /* [] */0
              ]);
  };
  var panelNavigation = Tea_html.nav(undefined, undefined, /* :: */[
        Tea_html.class$prime("panel-navigation"),
        /* [] */0
      ], /* :: */[
        panelTabButton(/* Input */0),
        /* :: */[
          panelTabButton(/* FragmentShader */1),
          /* [] */0
        ]
      ]);
  var match = model.tab;
  var panelContent;
  if (match) {
    var m = model.editor;
    panelContent = Tea_html.div(undefined, undefined, /* :: */[
          Tea_html.class$prime("panel"),
          /* [] */0
        ], /* :: */[
          viewFragmentShaderBlock(model, pass),
          /* :: */[
            m !== undefined ? Vdom.map((function (v) {
                      return /* EditorMsg */Block.__(4, [v]);
                    }), MonacoEditor.view(m)) : Tea_html.noNode,
            /* [] */0
          ]
        ]);
  } else {
    panelContent = Tea_html.div(undefined, undefined, /* :: */[
          Tea_html.class$prime("panel"),
          /* [] */0
        ], /* :: */[
          viewVertexDataBlock(model, pass),
          /* :: */[
            viewUniformDataBlock(model, pass),
            /* :: */[
              viewSamplerDataBlock(model, pass),
              /* [] */0
            ]
          ]
        ]);
  }
  return /* :: */[
          panelNavigation,
          /* :: */[
            panelContent,
            /* [] */0
          ]
        ];
}

var PassView = {
  tab: tab,
  setVertexInputData: setVertexInputData,
  setFragmentShaderFile: setFragmentShaderFile,
  setFragmentShaderFileSearchBox: setFragmentShaderFileSearchBox,
  editorMsg: editorMsg,
  init: init,
  update: update,
  vertexInputBlock: vertexInputBlock,
  viewVertexDataBlock: viewVertexDataBlock,
  viewUniformDataBlock: viewUniformDataBlock,
  viewSamplerDataBlock: viewSamplerDataBlock,
  customSearchBox: customSearchBox,
  viewFragmentShaderBlock: viewFragmentShaderBlock,
  view: view
};

function passWindow(param_0, param_1) {
  return /* PassWindow */[
          param_0,
          param_1
        ];
}

function fileTreeMsg(param_0) {
  return /* FileTreeMsg */Block.__(0, [param_0]);
}

function passListMsg(param_0) {
  return /* PassListMsg */Block.__(1, [param_0]);
}

function globalMsg(param_0) {
  return /* GlobalMsg */Block.__(2, [param_0]);
}

function passViewMsg(param_0) {
  return /* PassViewMsg */Block.__(3, [param_0]);
}

function getManifestPath(projectPath) {
  return Path.resolve(projectPath, "project-manifest.json");
}

function loadProject(projectPath) {
  var manifestPath = Path.resolve(projectPath, "project-manifest.json");
  if (Fs.existsSync(manifestPath)) {
    return AppDomain.Decode.project(Json.parseOrRaise(Fs.readFileSync(manifestPath, "utf8")));
  } else {
    return AppDomain.createProject(undefined);
  }
}

function init$1(param) {
  var projectPath = "./TestProject";
  var match = FileTree.init(Utils.Path.resolve(projectPath));
  return /* tuple */[
          {
            fileTree: match[0],
            global: Global.init(undefined),
            project: loadProject(projectPath),
            passList: PassList.init(undefined),
            mainWindow: /* Empty */0,
            basePath: Utils.Path.resolve(projectPath)
          },
          Tea_cmd.map((function (v) {
                  return /* FileTreeMsg */Block.__(0, [v]);
                }), match[1])
        ];
}

function whackOutModel(model) {
  var path = Path.resolve(Utils.Path.asString(model.basePath), "project-manifest.json");
  var fileContents = Json.stringify(AppDomain.Encode.project(model.project));
  return Utils.writeFile(path, fileContents);
}

function getSelectedPass(model) {
  var match = model.mainWindow;
  if (!match) {
    return ;
  }
  var n = match[0];
  return List.find((function (p) {
                return p.name === n;
              }), model.project.passes);
}

function update$1(model, msg) {
  whackOutModel(model);
  if (typeof msg === "number") {
    return model;
  }
  switch (msg.tag | 0) {
    case /* FileTreeMsg */0 :
        var fileTree = FileTree.update(model.fileTree, msg[0]);
        return {
                fileTree: fileTree,
                global: model.global,
                project: model.project,
                passList: model.passList,
                mainWindow: model.mainWindow,
                basePath: model.basePath
              };
    case /* PassListMsg */1 :
        var match = PassList.update(model.passList, msg[0]);
        var intent = match[1];
        var passList = match[0];
        if (typeof intent === "number") {
          return {
                  fileTree: model.fileTree,
                  global: model.global,
                  project: model.project,
                  passList: passList,
                  mainWindow: model.mainWindow,
                  basePath: model.basePath
                };
        }
        if (!intent.tag) {
          return {
                  fileTree: model.fileTree,
                  global: model.global,
                  project: model.project,
                  passList: passList,
                  mainWindow: /* PassWindow */[
                    intent[0],
                    init(undefined)
                  ],
                  basePath: model.basePath
                };
        }
        var p = intent[0];
        return {
                fileTree: model.fileTree,
                global: model.global,
                project: AppDomain.Project.createPass(model.project, p),
                passList: passList,
                mainWindow: /* PassWindow */[
                  p,
                  init(undefined)
                ],
                basePath: model.basePath
              };
    case /* GlobalMsg */2 :
        var globalState = Global.update(model.global, msg[0]);
        return {
                fileTree: model.fileTree,
                global: globalState,
                project: model.project,
                passList: model.passList,
                mainWindow: model.mainWindow,
                basePath: model.basePath
              };
    case /* PassViewMsg */3 :
        var match$1 = model.mainWindow;
        if (!match$1) {
          return Pervasives.failwith("wrong state");
        }
        var s = match$1[0];
        var match$2 = update(match$1[1], $$Option.unwrap(getSelectedPass(model)), msg[0]);
        var intent$1 = match$2[1];
        var passView = match$2[0];
        if (intent$1) {
          return {
                  fileTree: model.fileTree,
                  global: model.global,
                  project: AppDomain.Project.updatePass(model.project, s, intent$1[0]),
                  passList: model.passList,
                  mainWindow: /* PassWindow */[
                    s,
                    passView
                  ],
                  basePath: model.basePath
                };
        } else {
          return {
                  fileTree: model.fileTree,
                  global: model.global,
                  project: model.project,
                  passList: model.passList,
                  mainWindow: /* PassWindow */[
                    s,
                    passView
                  ],
                  basePath: model.basePath
                };
        }
    
  }
}

function sidebar(fileTree, passList) {
  return Tea_html.div(undefined, undefined, /* :: */[
              Tea_html.class$prime("sidebar"),
              /* [] */0
            ], /* :: */[
              Vdom.map((function (v) {
                      return /* PassListMsg */Block.__(1, [v]);
                    }), passList),
              /* :: */[
                Vdom.map((function (v) {
                        return /* FileTreeMsg */Block.__(0, [v]);
                      }), fileTree),
                /* [] */0
              ]
            ]);
}

function view$1(model) {
  var match = FileTree.view(model.fileTree);
  var param = PassList.view(model.passList, model.project.passes, $$Option.map((function (p) {
              return p.name;
            }), getSelectedPass(model)));
  var globalItems = List.concat(/* :: */[
        List.map((function (param) {
                return Vdom.map((function (v) {
                              return /* PassListMsg */Block.__(1, [v]);
                            }), param);
              }), param[1]),
        /* :: */[
          List.map((function (param) {
                  return Vdom.map((function (v) {
                                return /* FileTreeMsg */Block.__(0, [v]);
                              }), param);
                }), match[1]),
          /* [] */0
        ]
      ]);
  var match$1 = model.mainWindow;
  return Vdom.node(undefined, "transparent", undefined, undefined, /* :: */[
              Vdom.style("display", "contents"),
              /* [] */0
            ], List.concat(/* :: */[
                  /* :: */[
                    sidebar(match[0], param[0]),
                    /* [] */0
                  ],
                  /* :: */[
                    /* :: */[
                      Tea_html.div(undefined, undefined, /* :: */[
                            Tea_html.class$prime("main-view"),
                            /* [] */0
                          ], match$1 ? List.map((function (param) {
                                    return Vdom.map(passViewMsg, param);
                                  }), view(match$1[1], $$Option.unwrap(getSelectedPass(model)))) : /* [] */0),
                      /* [] */0
                    ],
                    /* :: */[
                      List.map((function (param) {
                              return Vdom.map((function (v) {
                                            return /* GlobalMsg */Block.__(2, [v]);
                                          }), param);
                            }), Global.view(model.global)),
                      /* :: */[
                        globalItems,
                        /* [] */0
                      ]
                    ]
                  ]
                ]));
}

function subscriptions(model) {
  return Tea_sub.batch(/* :: */[
              Tea_sub.map((function (m) {
                      return /* FileTreeMsg */Block.__(0, [m]);
                    }), FileTree.subscriptions(model.fileTree)),
              /* [] */0
            ]);
}

function rendererEntry(param) {
  return Tea_app.standardProgram({
              init: init$1,
              update: (function (model, msg) {
                  ((window.__elmModel = model));
                  return /* tuple */[
                          update$1(model, msg),
                          Tea_cmd.none
                        ];
                }),
              view: view$1,
              subscriptions: subscriptions
            }, Web_document.getElementById("app"), undefined);
}

var empty = /* Empty */0;

var noOp = /* NoOp */0;

exports.$great$great = $great$great;
exports.$less$less = $less$less;
exports.customSelect = customSelect;
exports.unsafe_getGlobalFileTree = unsafe_getGlobalFileTree;
exports.unsafe_getGlobalProject = unsafe_getGlobalProject;
exports.unsafe_getProjectBasePath = unsafe_getProjectBasePath;
exports.PassView = PassView;
exports.empty = empty;
exports.passWindow = passWindow;
exports.fileTreeMsg = fileTreeMsg;
exports.passListMsg = passListMsg;
exports.globalMsg = globalMsg;
exports.passViewMsg = passViewMsg;
exports.noOp = noOp;
exports.getManifestPath = getManifestPath;
exports.loadProject = loadProject;
exports.init = init$1;
exports.whackOutModel = whackOutModel;
exports.getSelectedPass = getSelectedPass;
exports.update = update$1;
exports.sidebar = sidebar;
exports.view = view$1;
exports.subscriptions = subscriptions;
exports.rendererEntry = rendererEntry;
/* fs Not a pure module */
