// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Path = require("path");

function absolute(path) {
  return {
          repr: path
        };
}

function resolve(path) {
  return {
          repr: Path.resolve(path, ".")
        };
}

function relative(a, b) {
  return Path.relative(a.repr, b.repr);
}

var extname = (function(p) {
        return require("path").extname(p.repr)
    });

function basename(file) {
  return Path.basename(file.repr);
}

function dirname(file) {
  return Path.dirname(file.repr);
}

function asString(file) {
  return file.repr;
}

function extend(path, segment) {
  return {
          repr: Path.resolve(path.repr, segment)
        };
}

var Path$1 = {
  absolute: absolute,
  resolve: resolve,
  relative: relative,
  extname: extname,
  basename: basename,
  dirname: dirname,
  asString: asString,
  extend: extend
};

var loadFile = (function (path) {
    let __impl = require("util").promisify(require("fs").readFile)
    return __impl(path, "utf-8")
});

var loadFileSync = (function (path) {
    return require("fs").readFileSync(path, "utf-8")
});

var writeFile = (function (path, content) {
    require("fs").writeFile(path, content, _ => undefined)
});

function getStaticAssetPath(name) {
  return name;
}

exports.Path = Path$1;
exports.loadFile = loadFile;
exports.loadFileSync = loadFileSync;
exports.writeFile = writeFile;
exports.getStaticAssetPath = getStaticAssetPath;
/* path Not a pure module */
