// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Path = require("path");

function absolute(path) {
  return {
          repr: path
        };
}

function resolve(path) {
  return {
          repr: Path.resolve(path, ".")
        };
}

function basename(file) {
  return Path.basename(file.repr);
}

function dirname(file) {
  return Path.dirname(file.repr);
}

function asString(file) {
  return file.repr;
}

function extend(path, segment) {
  return {
          repr: Path.resolve(path.repr, segment)
        };
}

var Path$1 = {
  absolute: absolute,
  resolve: resolve,
  basename: basename,
  dirname: dirname,
  asString: asString,
  extend: extend
};

function getStaticAssetPath(name) {
  return name;
}

exports.Path = Path$1;
exports.getStaticAssetPath = getStaticAssetPath;
/* path Not a pure module */
